In [1]:
list1=[5,8,9,7]
list2=[6,7,3,2]


In [2]:
import numpy as np


In [3]:
arr1=np.array(list1)
arr2=np.array(list2)

In [4]:
arr1+arr2

array([11, 15, 12,  9])

In [5]:
arr1.dtype

dtype('int32')

In [6]:
np.array([1,2,3,'4','5'])

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [7]:
arr2 =np.array([[1,2,3],[4,5,6],[7,8,9]])


In [8]:
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2.ndim


2

In [10]:
arr2.shape

(3, 3)

In [11]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr3=np.arange(4,20)

In [13]:
arr3.shape

(16,)

In [14]:
arr3.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [15]:
arr4=arr3

In [16]:
arr4 = arr4.reshape(4,4)

#### 

In [17]:
arr4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
arr3[5]

9

In [19]:
arr4[1:3,(1,2)]

array([[ 9, 10],
       [13, 14]])

In [21]:
arr5=np.array([[5,6,9],[-8,7,2],[-1,4,5]])

In [22]:
arr5

array([[ 5,  6,  9],
       [-8,  7,  2],
       [-1,  4,  5]])

In [23]:
arr5.sum()

29

In [25]:
arr5.mean()

3.2222222222222223

In [26]:
np.median(arr5)

5.0

In [27]:
arr5+10

array([[15, 16, 19],
       [ 2, 17, 12],
       [ 9, 14, 15]])

In [33]:
arr6=arr5*100

In [35]:
arr6=[[10,20,30,40],[80,90,60,50],[40,30,20,10]]

In [36]:
np.sqrt(arr6)

array([[3.16227766, 4.47213595, 5.47722558, 6.32455532],
       [8.94427191, 9.48683298, 7.74596669, 7.07106781],
       [6.32455532, 5.47722558, 4.47213595, 3.16227766]])

# special arrays

In [38]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])